info:
  app:
    name: Grain Service
    description: Coffee
  team:
    name: MyTeam
---
## Spring Settings
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: coffee-beans
    datasource:
      hikari:
        maximum-pool-size: 10
