server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    product:
      topic: "beans-topic"
    bootstrap-servers: localhost:9092,localhost:9094

    consumer:
      group-id: grainGroup
      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
#        spring.json.trusted.packages: com.example.core

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9099}
    negotiation-type: plaintext